### PR TITLE
Adds another js file for the reference code

### PR DESCRIPTION
**Pull request by niralikap**

### CODE REVIEW

**Comment by TottoMoe** [comment]
test

**Review by KevinRivera14 — APPROVED** [review]
LOOKS AMAZING 🤩

**Review by TottoMoe — APPROVED** [review]
test

**Review by emanuelm1 — APPROVED** [review]
looks good!!

**Comment by niralikap** [comment]
Removed the duplicate code and added the API query URLs for the receipt videos section.

**Pull request merged**
